### ISSUE TITLE
Can i set the default endian behaviour of each file?

### ISSUE THREAD

**Issue by timecop97** [dargueta/binobj#27]
My file contains lots of uint16_t's and a few char arrays. currently, I have to swap every other element in a char array and when declare ints as such:
`file_creation_year = binobj.UInt16(endian="little")`. Is there an option to set a default behaviour to swap every other byte? or to set the entire file with `endian=little`? 

Kind regards!

**Comment by dargueta** [comment]
> I have to swap every other element in a char array

I'm not completely sure what you mean here. Can you post some sample code?

> Is there an option to set a default behaviour to swap every other byte?

Do you mean in an integer? Do you mean `endian="big"`?

> or to set the entire file with endian=little?

I'm actually working on this for 0.10.0 right now 🙂. (It's unfortunately more difficult than I anticipated so I wouldn't hold my breath if I were you.)

**Comment by timecop97** [comment]
Thanks for the reply! 

I'm opening the file as a binary stream (`fdat = open("test.dat", "rb")`) and then passing that into my binobj struct using the `from_stream` method. I'm not sure what the copyright status is for the file i'm reading so I can't share the file, but for example the first element is a set of 4 bytes which in ascii spell out ABCD. When i try to read them as `magic = binobj.Bytes(const=b'ABCD')`, this causes an error, but when they are read with `magic = binobj.Bytes(const=b'BADC')`, this works correctly. There's also a field below it which contains a 16 bit integer. The documentation tells me that if the int reads as 0xCAB9 then all is well, but if it reads as 0xB9CA then an 'endianness swap is necessary'. This can presently be avoided by appending `endian='little'`,  but i feel like i've missed something. What i find weirdest is that the two bytes in the magic char string are swapped, but i guess that could be lazy encoding on the part of the programmer who designed the file, simply hardcoding the string as a 16 bit integer.

**Comment by dargueta** [comment]
> This can presently be avoided by appending endian='little'

Interesting... what is the value of `sys.byteorder` on your system?

> i guess that could be lazy encoding on the part of the programmer who designed the file, simply hardcoding the string as a 16 bit integer.

This is probably what happened.

**Comment by timecop97** [comment]
> Interesting... what is the value of sys.byteorder on your system?

Whoops, forgot to put that, it's 'little'. I guess if the issue is with weirdly encoded magic bytes I can just swap them on my end and let it be. Thanks for the help!

**Comment by dargueta** [comment]
No problem! You may have just given me an idea for toggling endianness with this... 🤔

**Comment by dargueta** [comment]
You may find some use in the features of [the latest release](https://github.com/dargueta/binobj/releases/tag/0.10.0).
